// User
export const FETCH_USERS = 'FETCH_USERS';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

// Reset Password
export const ResetPassWord = 'ResetPassWord';
export const FORM_SEND_MAIL_ON = 'FORM_SEND_MAIL_ON';
export const FORM_SEND_MAIL_OFF = 'FORM_SEND_MAIL_OFF';


// Vocabulary Topic
export const FETCH_VOCABULARY_TOPIC = 'FETCH_VOCABULARY_TOPIC';
export const ADD_VOCABULARY_TOPIC = 'ADD_VOCABULARY_TOPIC';
export const FORM_ADD_VOCA_TOPIC_ON = 'FORM_ADD_VOCA_TOPIC_ON';
export const FORM_ADD_VOCA_TOPIC_OFF = 'FORM_ADD_VOCA_TOPIC_OFF';
export const DELETE_VOCABULARY_TOPIC = 'DELETE_VOCABULARY_TOPIC';
export const FORM_EDIT_VOCA_TOPIC_ON = 'FORM_EDIT_VOCA_TOPIC_ON';
export const FORM_EDIT_VOCA_TOPIC_OFF = 'FORM_EDIT_VOCA_TOPIC_OFF';
export const GET_VOCA_TOPIC_ID = 'GET_VOCA_TOPIC_ID';
export const UPDATE_VOCABULARY_TOPIC = 'UPDATE_VOCABULARY_TOPIC';


// Vocabulary
export const FETCH_VOCABULARY_WITH_TOPIC = 'FETCH_VOCABULARY_WITH_TOPIC';
export const FORM_ADD_VOCA_ON = 'FORM_ADD_VOCA_ON';
export const FORM_ADD_VOCA_OFF = 'FORM_ADD_VOCA_OFF';
export const ADD_VOCABULARY = "ADD_VOCABULARY";
export const DELETE_VOCABULARY = "DELETE_VOCABULARY";
export const EDIT_VOCABULARY = 'EDIT_VOCABULARY';
export const GET_VOCA_ID = 'GET_VOCA_ID';
export const FORM_EDIT_VOCA_ON = 'FORM_EDIT_VOCA_ON';
export const FORM_EDIT_VOCA_OFF = 'FORM_EDIT_VOCA_OFF';

// Alert
export const ALERT_ADMIN_ON = 'ALERT_ADMIN_ON';
export const ALERT_ADMIN_OFF = 'ALERT_ADMIN_OFF';
//Course
export const FETCH_COURSES = 'FETCH_COURSES';
export const ADD_COURSE = 'ADD_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
//Chapter
export const FETCH_CHAPTERS = 'FETCH_CHAPTERS';
export const ADD_CHAPTER = 'ADD_CHAPTER';
export const EDIT_CHAPTER = 'EDIT_CHAPTER';
export const DELETE_CHAPTER = 'DELETE_CHAPTER';
export const UPDATE_CHAPTER = 'UPDATE_CHAPTER';
//Lesson
export const FETCH_LESSONS = 'FETCH_LESSONS';
export const ADD_LESSON = 'ADD_LESSON';
export const EDIT_LESSON = 'EDIT_LESSON';
export const DELETE_LESSON = 'DELETE_LESSON';
export const UPDATE_LESSON = 'UPDATE_LESSON';
